### ISSUE TITLE
3.00 version，error：arr.readUint16BE is not a function

### ISSUE THREAD

**Issue by huzhen-v5** [fontello/ttf2woff#19]
version  3.0.0 ，when i run ：ttf2woff fontello.ttf fontello.woff，console error  "arr.readUint16BE is not a function"。version 2.0.0 is ok

**Comment by puzrin** [comment]
Can not reproduce. Please provide details to reopen.

**Comment by rlidwka** [comment]
Are you using node.js, and if so, which version are you running?

Maybe you have some idea why it isn't a function here (maybe `global.Buffer` isn't something it should be)?:
https://github.com/fontello/ttf2woff/blob/1cfdbe6bb2cef1a0c168c209f664d5d1ce1322e2/index.js#L110

**Comment by huzhen-v5** [comment]
> Are you using node.js, and if so, which version are you running?
> 
> Maybe you have some idea why it isn't a function here (maybe `global.Buffer` isn't something it should be)?:
> https://github.com/fontello/ttf2woff/blob/1cfdbe6bb2cef1a0c168c209f664d5d1ce1322e2/index.js#L110

yes, i am using node.js, my version is 12.18.2. i think i know, my version is to low. which version do you running, and can execute successful?

**Comment by puzrin** [comment]
@huzhen-v5  I see this error in 12.18.2, but everything works in v12.22.1. So, just update your node to latest v12.

**Comment by huzhen-v5** [comment]
> @huzhen-v5 I see this error in 12.18.2, but everything works in v12.22.1. So, just update your node to latest v12.

thank  you, i updated my node to latest v12, and it works now.
